[package]
name = "csv2xlsx"
version = "0.1.0"
authors = ["Giacomo Rizzi <gufoes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xlsxwriter = "0.3"
csv = "1.1"
clap = "3.0.0-beta.1"
calamine = "0.16"
